name: 'worflow of the child repo'
on: 
  workflow_dispatch:
  repository_dispatch:
    types: [trigger_workflow]
jobs:
  trigger_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Echo worflow name
        shell: bash
        run: |
          echo " I am workflow of chiid repo"
          echo "Received payload: ${{ github.event.client_payload }}"
