name: 'Workflow of the Child REPO'

on: 
  repository_dispatch:
    types: [trigger_workflow]

jobs:
  trigger_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2  
        
      - name: testing the repo
        run: |
          echo "which repo"
          git remote -v
          git status
      - name: Echo workflow name and payload
        shell: bash
        run: |
          echo "I am workflow of child repo"
          echo "the branch name is : ${{ github.event.client_payload.branch_name }}"
          echo "path from the parent repo is: ${{ github.event.client_payload.path }}"
          echo "tag from the parent repo is: ${{ github.event.client_payload.tag }}"
          
      
