name: 'Workflow of the Child REPO'

on: 
  repository_dispatch:
    types: [trigger_workflow]

jobs:
  trigger_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2  
        
      - name: testing the repo
        run: |
          echo "which repo"
          git remote -v
          git status
      - name: Echo getting the values from the parent workflow to child workflow
        shell: bash
        run: |
          echo "I am workflow of child repo"
          echo "the branch anem is:${{ github.event.client_payload.branch_name }}"
          echo "path from the parent repo is: ${{ github.event.client_payload.path }}"
          echo "tag from the parent repo is: ${{ github.event.client_payload.tag }}"

      # - name: Determine if branch exists
      #   id: branch-check
      #   run: |
      #     if git show-ref "refs/heads/${branch_name}" > /dev/null; then
      #       echo "Branch exists"
      #       echo "::set-output name=branch_exists::true"
      #     else
      #       echo "Branch does not exist"
      #       echo "::set-output name=branch_exists::false"
      #     fi
  
      # - name: Create branch if not exists
      #   if: steps.branch-check.outputs.branch_exists == 'false'
      #   run: git checkout -b $branch_name
      - name: Check if branch exists if not create the branch
        run: |
          export BRANCHES=$(git branch -r)
          BRANCH_NAME_TO_CHECK="${{ github.event.client_payload.branch_name }}"
      
          if echo "$BRANCHES" | grep -q "origin/$BRANCH_NAME_TO_CHECK"; then
            echo "Branch $BRANCH_NAME_TO_CHECK exists."
          else
            git checkout -b $branch_name
            echo "$branch_name created"
          fi
              
          
      
