name: 'Workflow of the Child REPO'

on: 
  repository_dispatch:
    types: [trigger_workflow]

jobs:
  trigger_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2  
        
      - name: testing the repo
        run: |
          echo "which repo"
          git remote -v
          git status
      - name: Echo getting the values from the parent workflow to child workflow
        shell: bash
        run: |
          echo "I am workflow of child repo"
          branch_name=$(basename "${{ github.event.client_payload.branch_name }}")
          echo "the branch name is : $branch_name"
          echo "path from the parent repo is: ${{ github.event.client_payload.path }}"
          echo "tag from the parent repo is: ${{ github.event.client_payload.tag }}"

      - name: Check if branch exists and create if not exists
        run: |
          git remote -v
          git status
          if git show-ref --quiet "refs/heads/$branch_name"; then
            echo "Branch $branch_name exists."
          else
            echo "Branch $branch_name does not exist."
            echo "Creating branch $branch_name..."
            git checkout -b $branch_name
            git push origin $branch_name
            git branch | grep $branch_name
          fi
              
          
      
